default:
  # https://catboost.ai/docs/concepts/r-reference_catboost-train.html
  params:
    iterations: 500
    learning_rate: 0.01
    depth: 3
    loss_function: 'RMSE'
    eval_metric: 'RMSE'
    od_type: 'Iter'
    metric_period: 50
    od_wait: 20
    use_best_model: no
    train_dir: !expr tempfile("train_dir.")

