# https://xgboost.readthedocs.io/en/latest/parameter.html
default:
  params:
    # General Parameters
    booster: gbtree
    # Command Line Parameters
    nrounds: 100
    # Parameters for Tree Booster
    eta: 0.1
    gamma: 0
    max_depth: 10
    min_child_weight: 5
    subsample: 0.75
    colsample_bytree: 0.75
    lambda: 1
    alpha: 1
    # Learning Task Parameters reg:squarederror
    objective: reg:squarederror
    eval_metric: mae

